#!/bin/bash

# This is a script for determining the best predictor for Cantril Ladder Score written by Iliyas Akhmet (24038357)

# Assigning the variables

file=$1
all_predictors=("GDP per capita" "Population" "Homicide Rate" "Life Expectancy")
max_abs_correlation=0
best_predictor=""

# Checking the number of inputs
if [ $# != 1 ]; then
    echo "You entered $# files, the program requires 1."
    exit 1
fi

# Checking the existence of the file
if [ ! -f "$file" ]; then
    echo "File named $file doesn't exist."
    exit 1
fi

# Checking if the file has a content
if [ ! -s "$file" ]; then
    echo "File named $file is empty."
fi

# Storing the data into temporary file without the header
tail -n +2 "$file" > temp_file

# Looping through all predictors and calculating the correlations
for ((i=0; i<${#all_predictors[@]}; i++)); do
    predictor=$(($i + 4))
    correlation=$(awk -v predictor="$predictor" '
        BEGIN { FS="\t"; sum_x=0; sum_y=0; sum_xy=0; sum_xx=0; sum_yy=0; n=0 } # Initializing variables
        NR>1 {
	    if ($8 != "" && $predictor != "") {
                sum_x += $predictor
                sum_y += $8
                sum_xy += $predictor*$8
                sum_xx += $predictor*$predictor
                sum_yy += $8*$8
                n++
            }
        }
        END {
            mean_x = sum_x / n
            mean_y = sum_y / n
            covariance = (sum_xy - sum_x*mean_y) / n
            stddev_x = sqrt((sum_xx - sum_x*sum_x/n) / n)
            stddev_y = sqrt((sum_yy - sum_y*sum_y/n) / n)
	    correlation = covariance / (stddev_x * stddev_y)
            printf "%.3f\n", correlation
        }' temp_file)

    # Printing the mean correlation for the predictor
    echo "Mean correlation of ${all_predictors[$i]} with Cantril ladder is $correlation"
    # Identifying the maximum absolute correlation
    abs_correlation=$(echo "$correlation" | tr -d '-')
    if (( $(awk 'BEGIN {print ('$abs_correlation' > '$max_abs_correlation')}' ) )); then
        max_abs_correlation=$abs_correlation
        best_predictor="${all_predictors[$i]} (r = $correlation)"
    fi
done

# Printing the most predictive mean correlation
echo "Most predictive mean correlation with the Cantril ladder is $best_predictor"

# Removing the temporary file
rm temp_file
