#!/bin/bash

# This is a script for determining the best predictor for Cantril Ladder Score written by Iliyas Akhmet (24038357)

# Assigning the variables

file=$1

# Checking the number of inputs
if [ $# != 1 ]; then
	echo "You entered $# files, the program requires 1."
	exit 1
fi

# Checking the existance of the file
if [ ! -f "$file" ]; then
	echo "File named $file doesn't exist."
	exit 1
fi

# Checking if the file has a content
if [ ! -s "$file" ]; then
	echo "File named $file is empty."
fi
