#!/bin/bash

file_count=$#
all_files=$@


if [ "$file_count" != 3 ]; then
	echo "Enter 3 files, please"
	exit 1
fi

for file in $all_files; do
	header=$(head -n 1 "$file")
	if ! echo "$header" | grep -q $'\t'; then
		echo "$file is not tab-separated"
		exit 1
	fi
done
